#PostgreSQL connection settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: pogress
    password: 31875595
    driver-class-name: org.postgresql.Driver
# HikariCP settings
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolBooks
# JPA settings
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 15
        order_inserts: true
        generate_statistics: true
  show-sql: true
  oracle:
    persistence:
      unit: postgresql

